### ISSUE TITLE
Notification sound should be splitted for upper and lower level notification

### ISSUE THREAD

**Issue by CosmicDuck** [direc85/harbour-batterybuddy#9]
I want notified only 1 time for upper limit but very often for lower limit.
Would be nice you can split them.
You can use the smallest interval to switch off the notification and longest interval to notifiy only one time. (- sign for never, ∞ for one time)

**Comment by CosmicDuck** [comment]
This is a whish

**Comment by direc85** [comment]
That's a nice suggestion, and makes perfect sense! It shouldn't be too difficult to implement, but it still takes some time to do it, as it requires many new configuration file entries and refined logic.

I use the application so that the alert limits are outside the charger limits, so I don't hear the alarm unless the battery is really empty, and never for the upper limit, because charging stops before that. It's good to receive other use cases - such as only using the alerts, or using the alerts inside the charging limits.

**Comment by direc85** [comment]
Oops, I didn't actually implement the "once" behavior...

**Comment by direc85** [comment]
Implemented in aea2ef3 and fine-tuned in 041adb3 and f582d55.

**Comment by direc85** [comment]
Whoops! Should have been "Fixes issue 22" but this was fixed, too.
